#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Track files in dotfiles
##? Usage:
##?    ln <TARGET> <LINK_NAME>
##? Examples:
##?    dot ln ~/.zshrc ~/.dotfiles/shell/zsh/.zshrc
docs::parse "$@"

ln $TARGET $LINK_NAME
$target="~/"$(realpath --relative-to="$HOME" $TARGET)
$link_name=$(realpath --relative-to="$DOTFILES_PATH" $LINK_NAME)
yq --arg TARGET "$target" --arg LINK_NAME "$link_name" -y '.[2].link += {$LINK_NAME: $TARGET}' $DOTFILES_PATH/symlinks/conf.linux.yaml >| /tmp/conf.linux.yaml && mv /tmp/conf.linux.yaml $DOTFILES_PATH/symlinks/conf.linux.yaml
