#!/usr/bin/env bash 

set -euo pipefail 
source "$DOTLY_PATH/scripts/core/_main.sh" 

##? Decrypt a file with AES
##?
##? Usage:
##?    decrypt <file_path> <file_output>

docs::parse "$@"

gpg -o $file_output  $file_path
