#!/usr/bin/env bash 

set -euo pipefail 
source "$DOTLY_PATH/scripts/core/_main.sh" 

##? Encrypt a file
##?
##? Usage:
##?    encrypt <file_path>

docs::parse "$@"

gpg --encrypt -o $file_path -r hello@sanchezcarlosjr.com $file_path
